sdn-356 provide a way to configure inactivity probe interval for ovn-northd in ovn-k8s

diff --git a/dist/images/ovndb-raft-functions b/dist/images/ovndb-raft-functions
--- a/dist/images/ovndb-raft-functions
+++ b/dist/images/ovndb-raft-functions
@@ -137,10 +137,6 @@ set_election_timer () {
   return 0
 }
 
-# Note that ovn-nbctl set-connection can only be run by ovnkube-db-0 when it is still one-server cluster
-# and the rest of the servers have not joined. Otherwise, with ovnkube-db-0 alone in the multiple-servers
-# cluster, no leader can be elected and set-connection command would hung.
-# 
 # set_connection() could be called by ovnkube-db-0 when :
 #    1. it is first initiated, or
 #    2. it restarts after the initial start has failed
@@ -156,15 +152,36 @@ set_connection () {
 
   echo "add port ${port} to connection table and disable inactivity probe"
 
+  # this call will fail on non-leader node since we are using unix socket and no --no-leader-only option.
   output=$(ovn-${db}ctl --data=bare --no-headings --columns=target,inactivity_probe list connection 2>/dev/null)
   if [[ $? == 0 ]]; then
     target=$(echo "${output}" | awk "ORS=\",\"")
     if [[ "${target}" != "ptcp:${port},0," ]]; then
       ovn-${db}ctl --inactivity-probe=0 set-connection ptcp:${port}
       if [[ $? != 0 ]]; then
-        echo "Failed to set connection and disable inactivity probe"
-        echo "Exiting...."
+        echo "Failed to set connection and disable inactivity probe. Exiting...."
         exit 12
+      fi
+    fi
+  fi
+  return 0
+}
+
+set_northd_probe_interval () {
+  # OVN_NORTHD_PROBE_INTERVAL - probe interval of northd for NB and SB DB
+  # connections in ms (default 5000)
+  northd_probe_interval=${OVN_NORTHD_PROBE_INTERVAL:-5000}
+
+  echo "setting northd probe interval to ${northd_probe_interval} ms"
+
+  # this call will fail on non-leader node since we are using unix socket and no --no-leader-only option.
+  output=$(ovn-nbctl --if-exists get NB_GLOBAL . options:northd_probe_interval)
+  if [[ $? == 0 ]]; then
+    if [[ "${output}" != "\"${northd_probe_interval}\"" ]]; then
+      ovn-nbctl set NB_GLOBAL . options:northd_probe_interval=${northd_probe_interval}
+      if [[ $? != 0 ]]; then
+        echo "Failed to set northd probe interval to ${northd_probe_interval}. Exiting....."
+        exit 13
       fi
     fi
   fi
@@ -188,12 +205,6 @@ ovsdb-raft () {
   ovn_db_file=${OVN_ETCDIR}/ovn${db}_db.db
 
   rm -f ${ovn_db_pidfile}
-
-  if [[ ${election_timer} -lt 100 ]] || [[ ${election_timer} -gt 600000 ]]; then
-    echo "election timer must be between 100 and 600000, in msec"
-    echo "Exiting..."
-    exit 12
-  fi
 
   verify-ovsdb-raft
   local_ip=$(getent ahostsv4 $(hostname) | grep -v "^127\." | head -1 | awk '{ print $1 }')
@@ -228,11 +239,12 @@ ovsdb-raft () {
   echo "=============== ${db}-ovsdb-raft ========== RUNNING"
 
   if [[ "${POD_NAME}" == "ovnkube-db-0" ]] ; then
-    # setting election timer; do this before setting connection to prevent the other servers from
-    # joining the cluster if election timer setting fails.
-    # Note that election timer can only be set on cluster leader so we must do this when DB
-    # is one server cluster, as the result ovnkube-db-0 is the leader.
+    # set election timer value before other servers join the cluster. Note that the election timer can
+    # only be set on the leader so we must do this in ovnkube-db-0 when it is still single-node cluster
     set_election_timer ${election_timer}
+    if [[ ${db} == "nb" ]]; then
+      set_northd_probe_interval
+    fi 
     set_connection ${port}
   fi
 
